echo : dummy"
sudo: required
services:
- docker
language: ruby
before_install:
- sudo docker build -t quine-relay .
script:
- sudo docker run --privileged --name qr -t quine-relay
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sh .travis.yml
env:
  global:
    secure: NGDakAqRZgGJwEJTlXenhoXcq9ulf0X0fjnC+oF+ktTXCRpdbQd8+faxIW5DR26qF5OMWPqsLtUv8HtQyv5P5gVNs41hXygmNU1R9TOMpw64FjXtkD1HNf0D4jE2STuUU2xB+sCifeb9z6SvMpcy6ZswBlhAVnV+5dboNZL0Ww0=
dummy: |
  dummy" > /dev/null
